apiVersion: v1
name: gate
version: 1.2.2
tillerVersion: ">=2.4.0"
appVersion: 1.1.6
description: Single Sign On platform for centralised authentication across Linux, OpenVPN and CAS.
home: https://github.com/gate-sso/gate
sources:
- https://github.com/gate-sso/gate
